# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: hoverkraft-tech/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"
        up-flags: "--scale chrome=5"

    - name : install dependencies
      run: pip install  robotframework-pabot robotframework robotframework-seleniumlibrary

    - name : run tests
      run: pabot --testlevelsplit test.robot
    

